title: Growing in Data
author: Jenifer De Figueiredo
email: jeny@visualnarrativeds.com
description: > # this means to ignore newlines until "baseurl:"
 Baby data science nerd, honing skills while exploring data in this world...

# social links
twitter_username: @jendefig
github_username:  jendefig

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
